//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenimERP.Views.ComExInvoiceMaster.Reports {
    
    public partial class RPreShipmentInspectionCertificate : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent(string invNo) {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "DenimERP.Views.ComExInvoiceMaster.Reports.RPreShipmentInspectionCertificate.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.PageHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageHeaderBand>("PageHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.GroupFooter1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupFooterBand>("GroupFooter1");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.table4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table4");
            this.tableRow4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow4");
            this.tableCell8 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell8");
            this.tableCell12 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell12");
            this.tableCell10 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell10");
            this.label62 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label62");
            this.label103 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label103");
            this.label105 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label105");
            this.label106 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label106");
            this.label108 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label108");
            this.label109 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label109");
            this.label110 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label110");
            this.label111 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label111");
            this.label112 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label112");
            this.label113 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label113");
            this.label114 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label114");
            this.label115 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label115");
            this.label116 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label116");
            this.label117 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label117");
            this.label118 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label118");
            this.label119 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label119");
            this.label120 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label120");
            this.label121 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label121");
            this.label122 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label122");
            this.label123 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label123");
            this.label124 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label124");
            this.label125 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label125");
            this.label126 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label126");
            this.label127 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label127");
            this.label128 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label128");
            this.label129 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label129");
            this.label130 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label130");
            this.label131 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label131");
            this.label132 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label132");
            this.label133 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label133");
            this.label134 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label134");
            this.label135 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label135");
            this.label136 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label136");
            this.label137 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label137");
            this.label138 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label138");
            this.label139 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label139");
            this.table1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table1");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.tableRow1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow1");
            this.tableCell1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell1");
            this.tableCell2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell2");
            this.tableCell3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell3");
            this.table2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("table2");
            this.tableRow2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("tableRow2");
            this.tableCell4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell4");
            this.tableCell5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tableCell5");
            this.PageFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.PageFooterBand>("PageFooter");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");

            // Parameters
            this.INVNO.Value = invNo;

            // Data Sources
            this.sqlDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.Sql.SqlDataSource>("sqlDataSource1");

            // Calculated Fields
            this.calculatedField1 = reportInitializer.GetCalculatedField("calculatedField1");
            this.calculatedField2 = reportInitializer.GetCalculatedField("calculatedField2");
            this.calculatedField3 = reportInitializer.GetCalculatedField("calculatedField3");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.PageHeaderBand PageHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.GroupFooterBand GroupFooter1;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRTable table4;
        private DevExpress.XtraReports.UI.XRTableRow tableRow4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell8;
        private DevExpress.XtraReports.UI.XRTableCell tableCell12;
        private DevExpress.XtraReports.UI.XRTableCell tableCell10;
        private DevExpress.XtraReports.UI.XRLabel label62;
        private DevExpress.XtraReports.UI.XRLabel label103;
        private DevExpress.XtraReports.UI.XRLabel label105;
        private DevExpress.XtraReports.UI.XRLabel label106;
        private DevExpress.XtraReports.UI.XRLabel label108;
        private DevExpress.XtraReports.UI.XRLabel label109;
        private DevExpress.XtraReports.UI.XRLabel label110;
        private DevExpress.XtraReports.UI.XRLabel label111;
        private DevExpress.XtraReports.UI.XRLabel label112;
        private DevExpress.XtraReports.UI.XRLabel label113;
        private DevExpress.XtraReports.UI.XRLabel label114;
        private DevExpress.XtraReports.UI.XRLabel label115;
        private DevExpress.XtraReports.UI.XRLabel label116;
        private DevExpress.XtraReports.UI.XRLabel label117;
        private DevExpress.XtraReports.UI.XRLabel label118;
        private DevExpress.XtraReports.UI.XRLabel label119;
        private DevExpress.XtraReports.UI.XRLabel label120;
        private DevExpress.XtraReports.UI.XRLabel label121;
        private DevExpress.XtraReports.UI.XRLabel label122;
        private DevExpress.XtraReports.UI.XRLabel label123;
        private DevExpress.XtraReports.UI.XRLabel label124;
        private DevExpress.XtraReports.UI.XRLabel label125;
        private DevExpress.XtraReports.UI.XRLabel label126;
        private DevExpress.XtraReports.UI.XRLabel label127;
        private DevExpress.XtraReports.UI.XRLabel label128;
        private DevExpress.XtraReports.UI.XRLabel label129;
        private DevExpress.XtraReports.UI.XRLabel label130;
        private DevExpress.XtraReports.UI.XRLabel label131;
        private DevExpress.XtraReports.UI.XRLabel label132;
        private DevExpress.XtraReports.UI.XRLabel label133;
        private DevExpress.XtraReports.UI.XRLabel label134;
        private DevExpress.XtraReports.UI.XRLabel label135;
        private DevExpress.XtraReports.UI.XRLabel label136;
        private DevExpress.XtraReports.UI.XRLabel label137;
        private DevExpress.XtraReports.UI.XRLabel label138;
        private DevExpress.XtraReports.UI.XRLabel label139;
        private DevExpress.XtraReports.UI.XRTable table1;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRTableRow tableRow1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell1;
        private DevExpress.XtraReports.UI.XRTableCell tableCell2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell3;
        private DevExpress.XtraReports.UI.XRTable table2;
        private DevExpress.XtraReports.UI.XRTableRow tableRow2;
        private DevExpress.XtraReports.UI.XRTableCell tableCell4;
        private DevExpress.XtraReports.UI.XRTableCell tableCell5;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.CalculatedField calculatedField1;
        private DevExpress.XtraReports.UI.CalculatedField calculatedField2;
        private DevExpress.XtraReports.UI.CalculatedField calculatedField3;
        private DevExpress.XtraReports.Parameters.Parameter INVNO;
        private DevExpress.XtraReports.UI.PageFooterBand PageFooter;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
    }
}
